# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11 ]
        distro: [ 'zulu', 'temurin' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java-version }} ${{ matrix.distro }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.distro }}
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
